package org.cafydia.android.bedcasearch;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

/**
 * Created by user on 19/08/14.
 */
public class SQLOpenHelperBedca extends android.database.sqlite.SQLiteOpenHelper  {
    public static final String DATABASE_NAME = "bedca_database_mirror";
    private static final int VERSION = 1;

    private static final String schema =
            "CREATE TABLE food(bedca_id INTEGER, name_en TEXT, name_es TEXT, carbohydrates REAL);";

    public SQLOpenHelperBedca(Context context) {
        super(context, DATABASE_NAME, null, VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(schema);

        for(String[] fields : mFoods){
            db.execSQL("INSERT INTO food (bedca_id, name_en, name_es, carbohydrates) VALUES (?, ?, ?, ?)", fields);
        }
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }

    private static final String[][] mFoods = new String[][] {
            new String[] { "1070", "Barley bread", "Pan de cebada", "39.9" },
            new String[] { "2161", "Bread, sliced, toasted", "Pan blanco, de molde, tostado", "45.7" },
            new String[] { "2164", "Bread, whole wheat, sliced, toasted", "Pan integral, de molde, tostado", "44.0" },
            new String[] { "2569", "Breadcrumbed fried loin, ham and cheese", "San jacobo, congelado", "25.16" },
            new String[] { "2171", "Breadcrumbs", "Pan rallado", "51.5" },
            new String[] { "2290", "Breaded chicken, fried", "Pollo empanado, frito", "5.34" },
            new String[] { "2174", "Burguer bread", "Pan, tipo hamburguesa", "47.5" },
            new String[] { "1071", "Corn bread", "Pan de maíz", "48.1" },
            new String[] { "2168", "Milk bread", "Pan de leche", "52.1" },
            new String[] { "1067", "Oat bread", "Pan de avena", "48.5" },
            new String[] { "2615", "Pork loin, cheese and ham roll, breaded, fried, flamenquin type", "Flamenquín", "4.4" },
            new String[] { "2167", "Rye bread", "Pan de centeno", "45.8" },
            new String[] { "2160", "White bread", "Pan blanco, de barra", "47.0" },
            new String[] { "1066", "White bread, baguette type", "Pan blanco, tipo baguette", "55.9" },
            new String[] { "2162", "White bread, fried", "Pan blanco, frito", "51.5" },
            new String[] { "2165", "White bread, toasted", "Pan blanco, tostado", "59.2" },
            new String[] { "2166", "White bread, toasted, without salt", "Pan blanco, tostado sin sal", "59.2" },
            new String[] { "1064", "White bread, without salt", "Pan blanco, de barra, sin sal", "53.9" },
            new String[] { "2170", "Whole bread, toasted", "Pan integral, tostado", "48.7" },
            new String[] { "2163", "Whole wheat bread", "Pan integral", "44.0" },
            new String[] { "2173", "Whole wheat bread, toast", "Pan tostado integral", "59.2" },
            new String[] { "2169", "Whole wheat bread, without salt", "Pan integral, sin sal", "44.0" },
            new String[] { "2484", "san millan creamy cheese", "Cremoso san millan", "3.0" },
            new String[] { "2427", "Aguardiente", "Aguardiente", "0.0" },
            new String[] { "2314", "Albacore in vegetable oil", "Bonito en aceite vegetal", "0.0" },
            new String[] { "802", "Albacore, canned in oil, drained", "Bonito, enlatado en aceite, escurrido", "0.0" },
            new String[] { "801", "Albacore, canned, soybean oil", "Bonito del norte, enlatado en aceite de soja", "0.0" },
            new String[] { "800", "Albacore, steamed", "Bonito del norte, al vapor", "0.0" },
            new String[] { "2490", "Almond milk", "Leche de almendra", "60.0" },
            new String[] { "2188", "Almond, cream", "Crema de almendras", "59.7" },
            new String[] { "897", "Almond, fried, salted", "Almendra, frita, salada", "4.5" },
            new String[] { "896", "Almond, raw", "Almendra, cruda", "6.2038" },
            new String[] { "2181", "Almond, raw, in shell", "Almendra, cruda, con cáscara", "5.36" },
            new String[] { "2182", "Almond, toast", "Almendra, tostada", "6.6" },
            new String[] { "2316", "Anchovy", "Boquerón", "0.0" },
            new String[] { "2129", "Anchovy in vegetable oil", "Anchoas en aceite vegetal", "0.0" },
            new String[] { "2318", "Anchovy, fried", "Boquerón, frito", "0.5" },
            new String[] { "1022", "Anisette, dry", "Anís, seco", "1.0" },
            new String[] { "2634", "Annular seabream, raw", "Sargo, crudo", "0.0" },
            new String[] { "2231", "Apple", "Manzana", "12.0" },
            new String[] { "1078", "Apple cake", "Pastel de manzana", "57.4" },
            new String[] { "2467", "Apple juice", "Zumo de manzana", "11.0" },
            new String[] { "2556", "Apple vinegar", "Vinagre de manzana", "0.6" },
            new String[] { "2218", "Apricot", "Albaricoque", "9.5" },
            new String[] { "2444", "Apricot liqueur", "Licor apricot", "30.0" },
            new String[] { "1106", "Apricot nectar", "Néctar de albaricoque, envasado", "13.8" },
            new String[] { "2363", "Artichoke, canned", "Alcachofas en conserva", "1.2" },
            new String[] { "1176", "Artichoke, frozen, raw", "Alcachofa, cruda", "2.26" },
            new String[] { "2418", "Arugula", "Rúcula", "3.65" },
            new String[] { "1179", "Asparagus, green", "Espárrago, verde", "2.0" },
            new String[] { "2393", "Asparagus, white, canned", "Esparragos blancos en conserva", "3.4" },
            new String[] { "2370", "Aubergine", "Berenjena", "3.8" },
            new String[] { "730", "Aubergine, fried, in sunflowerseed oil", "Berenjena, frita, en aceite de girasol", "2.70609" },
            new String[] { "2216", "Avocado", "Aguacate", "5.9" },
            new String[] { "2217", "Avocado, frozen", "Aguacate congelado", "1.9" },
            new String[] { "2330", "Baby clam", "Chirla", "0.0" },
            new String[] { "2329", "Baby squid", "Chipiron", "0.7" },
            new String[] { "2317", "Bacon", "Tocino", "0.0" },
            new String[] { "2283", "Bacon, fried", "Panceta, frita", "0.0" },
            new String[] { "2260", "Bacon, raw", "Cerdo, panceta, cruda", "0.5" },
            new String[] { "682", "Bacon, raw, with separable fat", "Bacon, crudo, con grasa separable", "0.09" },
            new String[] { "680", "Bacon, smoked, grilled", "Bacón, ahumado, a la parrilla", "0.0" },
            new String[] { "2172", "Baguette", "Pan tipo baguette", "50.6" },
            new String[] { "2665", "Bakery", "Bollería, genérico", "52.8" },
            new String[] { "2557", "Balsamic vinegar", "Vinagre balsámico", "17.03" },
            new String[] { "2369", "Bamboo, raw", "Bambú, crudo", "5.2" },
            new String[] { "2245", "Banana", "Plátano", "20.0" },
            new String[] { "2581", "barbecue sauce", "Salsa barbacoa", "37.81" },
            new String[] { "1056", "Barley flour", "Harina de cebada", "74.5" },
            new String[] { "1014", "Barley, raw", "Cebada, cruda", "64.0" },
            new String[] { "2473", "Basil", "Albahaca", "20.5" },
            new String[] { "2603", "bay, leaf", "Laurel, hoja", "48.6" },
            new String[] { "2616", "Bean, stew fabada type", "Fabada", "13.42" },
            new String[] { "2580", "bechamel sauce", "Salsa bechamel", "10.8" },
            new String[] { "973", "Beef, heart, cooked", "Corazón, de vaca/buey, cocido", "0.0" },
            new String[] { "1024", "Beef, heart, raw", "Corazón, de vaca/buey, crudo", "0.0" },
            new String[] { "2265", "Beef, heart, raw", "Corazon de vaca, crudo", "0.0" },
            new String[] { "995", "Beef, part n/e, roasted, with separable fat", "Vaca/buey, parte s/e, asado", "0.0" },
            new String[] { "997", "Beef, part n/e, stewed, with separable fat", "Vaca/buey, parte s/e, estofado", "0.0" },
            new String[] { "996", "Beef, sirloin, grilled", "Vaca/buey, solomillo, a la plancha", "0.0" },
            new String[] { "981", "Beef, sirloin, raw", "Vaca/buey, solomillo, crudo", "0.0" },
            new String[] { "2437", "Beer", "Cerveza con alcohol", "3.12" },
            new String[] { "2439", "Beer, low alcohol", "Cerveza, baja en alcohol", "2.1" },
            new String[] { "1108", "Beer, stout, 8°- 9°", "Cerveza, oscura, 8°- 9°", "5.25714" },
            new String[] { "2416", "beetroot, canned", "Remolacha, en conserva", "5.6" },
            new String[] { "2445", "Benedictine liqueur", "Licor benedictine", "33.0" },
            new String[] { "2368", "Bilberry", "Arandano", "6.05" },
            new String[] { "1048", "Biscuit, fruit jam filled, comercial", "Galleta, barquillo, con jalea de frutas", "73.0" },
            new String[] { "1091", "Black currant juice", "Zumo de grosella negra", "7.6" },
            new String[] { "1185", "Black currant, raw", "Grosella negra, cruda", "7.10333" },
            new String[] { "2590", "Black pepper", "Pimienta, negra", "38.3" },
            new String[] { "2280", "Blood sausage", "Morcilla", "3.2" },
            new String[] { "2281", "Blood sausage, fried", "Morcilla, frita", "15.0" },
            new String[] { "2498", "Blue cheese", "Queso azul", "0.0" },
            new String[] { "2282", "Bologna", "Mortadela", "3.0" },
            new String[] { "2579", "Bolognese sauce", "Salsa boloñesa", "3.4" },
            new String[] { "2371", "Borage", "Borraja", "3.06" },
            new String[] { "1080", "Brain, lamb, raw", "Sesos, de cordero, crudos", "0.0" },
            new String[] { "1075", "Brain, pork, raw", "Sesos, de cerdo, crudos", "0.0" },
            new String[] { "1047", "Brain, veal, raw", "Sesos, de ternera, crudos", "0.0" },
            new String[] { "1032", "Breakfast cereal, corn and wheat", "Cereales desayuno base de maíz y trigo", "80.8" },
            new String[] { "1031", "Breakfast cereal, corn with honey", "Cereales desayuno base de maíz y miel", "83.0" },
            new String[] { "1042", "Breakfast cereal, corn with sugar", "Cereales desayuno, maíz azucarado", "88.0" },
            new String[] { "1188", "Breakfast cereal, corn, wheat and oat", "Cereales desayuno base de maíz, trigo y avena", "80.9" },
            new String[] { "2155", "Breakfast cereal, granola", "Cereales desayuno base muesli", "65.8" },
            new String[] { "1018", "Breakfast cereal, rice with chocolate", "Cereales desayuno base de arroz chocolateado", "86.6" },
            new String[] { "1026", "Breakfast cereal, rice with honey", "Cereales desayuno base de arroz y miel", "87.0" },
            new String[] { "1028", "Breakfast cereal, rice, wheat and fruit", "Cereales desayuno base de arroz, trigo y fruta", "76.6" },
            new String[] { "1036", "Breakfast cereal, wheat and fruit", "Cereales desayuno base de trigo y frutas", "71.0" },
            new String[] { "1038", "Breakfast cereal, wheat and honey", "Cereales desayuno base de trigo y miel", "88.0" },
            new String[] { "1035", "Breakfast cereal, wheat and rice", "Cereales desayuno base de trigo y arroz", "75.0" },
            new String[] { "1034", "Breakfast cereal, wheat with sugar", "Cereales desayuno base de trigo azucarado", "84.0" },
            new String[] { "1039", "Breakfast cereal, wheat, oat, corn and honey", "Cereales desayuno base de trigo, avena, maiz y miel", "79.0" },
            new String[] { "1040", "Breakfast cereal, wheat, oat, corn, honey and nuts", "Cereales desayuno base de trigo, avena, maíz, miel y nueces", "80.0" },
            new String[] { "1119", "Breakfast cereal, whole wheat, all bran type", "Cereales para el desayuno, ricos en fibra, tipo all-bran", "45.6" },
            new String[] { "2666", "Breakfast cereals, wheat and chocolate", "Cereales base trigo y chocolate", "81.0" },
            new String[] { "2499", "Brie cheese", "Queso brie", "0.0" },
            new String[] { "1123", "Broad bean, dried", "Haba, seca", "58.3" },
            new String[] { "1128", "Broad bean, dried, steeped, boiled", "Haba, seca, remojada, hervida", "7.2" },
            new String[] { "2194", "Broad bean, fresh", "Haba, fresca", "8.6" },
            new String[] { "2195", "Broad bean, fried", "Haba, frita", "8.6" },
            new String[] { "2372", "Broccoli, boiled", "Brécol, hervido", "1.1" },
            new String[] { "1177", "Broccoli, raw", "Brécol, crudo", "2.4" },
            new String[] { "1180", "Brussels sprout, frozen", "Col de bruselas, cruda", "3.5" },
            new String[] { "2254", "Butifarra sausage", "Butifarra", "5.5" },
            new String[] { "1052", "Butter cookie", "Galletas, de mantequilla", "68.0" },
            new String[] { "756", "Butter with salt", "Mantequilla salada", "0.5" },
            new String[] { "2550", "Butter, light", "Mantequilla, baja en calorías", "0.0" },
            new String[] { "2159", "Butterfly cookies", "Palmera", "61.0" },
            new String[] { "2417", "Cabbage", "Repollo", "3.7" },
            new String[] { "2386", "Cabbage, white, raw", "Col blanca, cruda", "2.54" },
            new String[] { "2501", "Cabrales cheese", "Queso cabrales", "0.0" },
            new String[] { "2658", "Cake", "Pastel", "49.2" },
            new String[] { "929", "Camembert cheese, 20-30% fidm", "Queso Camembert 20-30% MG/ES", "0.0" },
            new String[] { "930", "Camembert cheese, 60% fidm", "Queso camembert 60% mg/es", "0.0" },
            new String[] { "2645", "Candy", "Caramelo", "95.0" },
            new String[] { "2641", "Canned clams", "Almejas en conserva", "1.5" },
            new String[] { "2478", "Canneloni", "Canelones", "9.7" },
            new String[] { "2364", "Caper", "Alcaparra", "2.1" },
            new String[] { "876", "Caramel custard cream, diet", "Flan de huevo, bajo en calorías", "7.9" },
            new String[] { "858", "Carbonara sauce", "Salsa carbonara", "2.01" },
            new String[] { "1098", "Carbonated drink, lemon", "Refresco, sabor limón, con gas", "11.3361" },
            new String[] { "2380", "Cardoon", "Cardo", "3.5" },
            new String[] { "2327", "Cardoon, stalk, canned", "Cardo, tallo, en conserva", "2.4" },
            new String[] { "811", "Carp, baked", "Carpa, al horno", "0.0" },
            new String[] { "812", "Carp, raw", "Carpa, cruda", "0.0" },
            new String[] { "2252", "Carrot, fresh juice", "Zumo de zanahoria, fresco", "4.75" },
            new String[] { "2424", "Carrot, raw", "Zanahoria, cruda", "7.0" },
            new String[] { "922", "Cashew nut, raw", "Anacardo, crudo", "32.0" },
            new String[] { "2483", "Catalan creme", "Crema catalana", "15.48" },
            new String[] { "2387", "Cauliflower, boiled", "Coliflor, hervida", "2.04" },
            new String[] { "859", "Cauliflower, frozen, raw", "Coliflor, congelada, cruda", "2.1" },
            new String[] { "2338", "Caviar", "Caviar", "4.0" },
            new String[] { "739", "Celery, canned, in brine", "Apio, en conserva en salmuera", "1.3" },
            new String[] { "2366", "Celery, raw", "Apio, crudo", "1.5" },
            new String[] { "2662", "Cereal bar, with chocolate", "Barrita cereales con chocolate", "73.0" },
            new String[] { "767", "Cereal bar, with corn and wheat", "Barrita cereales maíz y trigo", "68.3" },
            new String[] { "2663", "Cereal bar, with fruit", "Barrita cereales con frutas", "78.0" },
            new String[] { "768", "Cereal bar, with wheat and chocolate", "Barrita cereales trigo y chocolate", "66.6" },
            new String[] { "2360", "Chard, boiled", "Acelgas, hervidas", "4.37" },
            new String[] { "2212", "Chard, raw", "Acelga, cruda", "2.7" },
            new String[] { "2221", "Chayote, raw", "Chayote, crudo", "4.51" },
            new String[] { "1005", "Cheddar cheese", "Queso Cheddar", "0.1" },
            new String[] { "2503", "Cheese", "Queso de bola", "0.0" },
            new String[] { "2508", "Cheese manchego type", "Queso manchego", "0.5" },
            new String[] { "2577", "cheese sauce", "Salsa de queso", "8.4" },
            new String[] { "948", "Cheese spread, plain, light", "Queso para untar, natural, bajo en calorías", "4.2" },
            new String[] { "947", "Cheese spread, with salmon", "Queso para untar, con salmón", "3.1" },
            new String[] { "945", "Cheese spread, with spice and herbs  ", "Queso para untar, con finas hierbas", "3.1" },
            new String[] { "691", "Cheese, afuega'l pitu type", "Queso afuega'l pitu", "0.0" },
            new String[] { "692", "Cheese, ahumado de aliva type", "Queso ahumado de aliva", "0.0" },
            new String[] { "705", "Cheese, aracena type", "Queso de aracena", "0.0" },
            new String[] { "716", "Cheese, arzúa type", "Queso de arzúa", "2.0" },
            new String[] { "696", "Cheese, cádiz type", "Queso de cádiz", "0.0" },
            new String[] { "693", "Cheese, cantabria type", "Queso cantabria", "0.0" },
            new String[] { "694", "Cheese, casin type", "Queso casín", "0.0" },
            new String[] { "715", "Cheese, castellano type", "Queso Castellano", "0.0" },
            new String[] { "700", "Cheese, cebreiro type", "Queso cebreiro", "0.0" },
            new String[] { "703", "Cheese, flor de guía type", "Queso flor de guía", "0.0" },
            new String[] { "704", "Cheese, gate-hurdes type", "Queso gata-hurdes", "0.0" },
            new String[] { "698", "Cheese, gaztazarra type", "Queso gaztazarra", "0.0" },
            new String[] { "711", "Cheese, grazalema type", "Queso grazalema", "0.0" },
            new String[] { "699", "Cheese, herreño type", "Queso herreño", "0.0" },
            new String[] { "717", "Cheese, ibores type", "Queso Ibores", "0.0" },
            new String[] { "718", "Cheese, mahón type", "Queso Mahón", "0.0" },
            new String[] { "722", "Cheese, majorero type", "Queso majorero", "0.0" },
            new String[] { "942", "Cheese, manchego type, in oil", "Queso manchego, en aceite", "0.0" },
            new String[] { "695", "Cheese, murcia with wine type", "Queso de murcia, al vino", "0.0" },
            new String[] { "708", "Cheese, pasiego type", "Queso pasiego", "0.0" },
            new String[] { "701", "Cheese, pedroches type", "Queso pedroches", "0.0" },
            new String[] { "709", "Cheese, peñamellera type", "Queso peñamellera", "0.0" },
            new String[] { "713", "Cheese, picón type", "Queso picón", "0.0" },
            new String[] { "712", "Cheese, porrúa type", "Queso porrúa", "0.0" },
            new String[] { "721", "Cheese, san simón type", "Queso San Simón", "0.0" },
            new String[] { "714", "Cheese, serrat type", "Queso serrat", "0.0" },
            new String[] { "710", "Cheese, servilleta type", "Queso servilleta", "0.0" },
            new String[] { "706", "Cheese, tenerife type", "Queso de tenerife", "0.0" },
            new String[] { "697", "Cheese, tetilla type", "Queso Tetilla", "0.0" },
            new String[] { "707", "Cheese, tiétar type", "Queso de tiétar", "0.0" },
            new String[] { "720", "Cheese, torta del casar type", "Queso torta del casar", "0.0" },
            new String[] { "702", "Cheese, tupí type", "Queso tupí", "0.0" },
            new String[] { "719", "Cheese, zamorano type", "Queso Zamorano", "0.0" },
            new String[] { "2504", "Cheese, edam type", "Queso edam", "0.0" },
            new String[] { "2220", "Cherry", "Cereza", "13.5" },
            new String[] { "2511", "Chesee spread", "Queso para untar", "2.3" },
            new String[] { "2187", "Chestnut", "Castaña, cruda", "36.5" },
            new String[] { "935", "Chestnut, roasted", "Castaña, tostada", "39.7" },
            new String[] { "2649", "Chewing gum", "Chicle, sin azúcar", "0.0" },
            new String[] { "2268", "Chicken croquettes", "Croquetas de pollo", "20.43" },
            new String[] { "2293", "Chicken luncheon meat", "Pollo, fiambre", "2.3" },
            new String[] { "2294", "Chicken luncheon meat, low fat", "Pollo, fiambre, bajo en grasa", "1.7" },
            new String[] { "994", "Chicken, breast, with skin, raw", "Pollo, pechuga, con piel, crudo", "0.0" },
            new String[] { "2295", "Chicken, fried", "Pollo, frito", "0.74" },
            new String[] { "993", "Chicken, leg, with skin, raw", "Pollo, muslo, con piel, crudo", "0.0" },
            new String[] { "992", "Chicken, leg, with skin, roasted", "Pollo, muslo, con piel, asado", "0.0" },
            new String[] { "2292", "chicken, whole, with skin, raw", "Pollo, entero, con piel, crudo", "0.0" },
            new String[] { "980", "Chicken, whole, with skin, roasted", "Pollo, entero, con piel, asado", "0.0" },
            new String[] { "2291", "Chicken, wing, with skin, raw", "Pollo, ala, con piel, cruda", "0.0" },
            new String[] { "2192", "Chickpea, boiled", "Garbanzo, hervido", "55.8" },
            new String[] { "2191", "Chickpea, canned", "Garbanzo, en conserva", "14.12" },
            new String[] { "1020", "Chickpea, dried, raw", "Garbanzo, seco, crudo", "49.2463" },
            new String[] { "733", "Chicory, raw", "Achicoria, cruda", "2.8" },
            new String[] { "2547", "Chiken fat", "Grasa de pollo", "0.0" },
            new String[] { "2297", "Chiken, breast, grilled", "Pollo, pechuga, plancha", "0.0" },
            new String[] { "2296", "Chiken, part not specified", "Pollo, parte sin especificar", "0.0" },
            new String[] { "2610", "Chili or hot pepper", "Guindilla, picante", "6.7" },
            new String[] { "2611", "Chili or hotpepper, powder", "Guindilla, en polvo", "31.7" },
            new String[] { "794", "Chili pepper, green", "Chile, verde", "2.6" },
            new String[] { "793", "Chili pepper, red", "Chile, rojo", "6.4" },
            new String[] { "2587", "Chinese spring roll", "Rollito de primavera", "27.29" },
            new String[] { "2594", "Chips", "Patatas, fritas, chips", "49.5" },
            new String[] { "2262", "Chistorra sausage", "Chistorra", "0.9" },
            new String[] { "2647", "Chocolate", "Bombón", "66.0" },
            new String[] { "903", "Chocolate and cream pudding", "Crema de chocolate y nata", "9.9" },
            new String[] { "766", "Chocolate bar, type bounty", "Barra chocolate, tipo bounty", "58.0" },
            new String[] { "770", "Chocolate bar, type kit kat", "Barra de chocolate, tipo Kit-kat", "63.0" },
            new String[] { "769", "Chocolate bar, type mars", "Barra de chocolate, tipo Mars", "65.9" },
            new String[] { "782", "Chocolate bitter, with sugar", "Chocolate negro, con azúcar", "63.0" },
            new String[] { "1116", "Chocolate cake", "Pastel de chocolate", "41.77" },
            new String[] { "902", "Chocolate cream, low calorie", "Crema de chocolate, baja en calorías", "13.9" },
            new String[] { "2487", "Chocolate ice cream", "Helado de chocolate", "28.2" },
            new String[] { "2496", "Chocolate mousse", "Mousse de chocolate", "37.8" },
            new String[] { "783", "Chocolate paste with hazelnuts", "Crema de chocolate con avellanas", "56.02" },
            new String[] { "778", "Chocolate with macadamian nuts", "Chocolate con nueces de macadamia", "47.6" },
            new String[] { "776", "Chocolate with milk and almonds", "Chocolate con leche y almendras", "49.8" },
            new String[] { "777", "Chocolate with milk and rice", "Chocolate con leche y arroz", "63.0" },
            new String[] { "788", "Chocolate, bitter", "Chocolate, negro", "64.8" },
            new String[] { "781", "Chocolate, bitter, with almonds", "Chocolate negro, con almendras", "41.5" },
            new String[] { "2264", "Chorizo", "Chorizo", "1.9" },
            new String[] { "2477", "Cinnamon, powder", "Canela, en polvo", "80.59" },
            new String[] { "2640", "Clams", "Almeja", "0.0" },
            new String[] { "2306", "Cockles", "Berberechos", "0.0" },
            new String[] { "2307", "Cockles, canned ", "Berberechos en conserva", "0.0" },
            new String[] { "901", "Coconut cream", "Crema de coco", "19.1" },
            new String[] { "911", "Coconut milk", "Leche de coco", "2.8" },
            new String[] { "748", "Coconut oil", "Aceite de coco", "0.0" },
            new String[] { "908", "Coconut, dried", "Coco, desecado", "11.8" },
            new String[] { "909", "Coconut, raw", "Coco, fresco", "15.2" },
            new String[] { "755", "Cod liver oil", "Aceite de hígado de bacalao", "0.0" },
            new String[] { "795", "Cod, fresh, baked", "Bacalao, fresco, al horno", "0.0" },
            new String[] { "2302", "Cod, raw", "Bacalao, crudo", "0.0" },
            new String[] { "1163", "Cod, salted, raw", "Bacalao, salado, crudo", "0.0" },
            new String[] { "797", "Cod, salted, steeped, raw", "Bacalao, salado, remojado, crudo", "0.0" },
            new String[] { "745", "Cod, smoked", "Bacalao, ahumado", "0.0" },
            new String[] { "2304", "Codfish, fried", "Bacalao, frito", "0.0" },
            new String[] { "681", "Coffee infusion, with milk", "Café, con leche", "2.45" },
            new String[] { "2447", "Coffee liqueur", "Licor de café", "46.8" },
            new String[] { "2433", "Coffee, brewed", "Café, infusión", "0.0" },
            new String[] { "2434", "Coffee, brewed, decaffeinated", "Café, infusión, descafeinado", "0.0" },
            new String[] { "1109", "Coffee, powder", "Café, en polvo, sin reconstituir", "8.0" },
            new String[] { "1019", "Coffee, seed or powder, descaffeinated", "Café, en grano o molido, descafeinado", "30.4" },
            new String[] { "2435", "Coffee, substitute, instant", "Café, sucedáneo, soluble", "80.9" },
            new String[] { "1107", "Cognac", "Coñac", "0.0" },
            new String[] { "2451", "Cola drink, carbonated, decaffeinated", "Refresco con gas, sabor cola, sin cafeina", "10.75" },
            new String[] { "2452", "Cola drink, light, carbonated, decaffeinated", "Refresco con gas, sabor cola, sin cafeina, bajo en calorías", "0.1" },
            new String[] { "2614", "Cold vegetal soup, gazpacho", "Gazpacho", "1.6" },
            new String[] { "2332", "Conger", "Congrio", "0.0" },
            new String[] { "2272", "Cooked ham, canned", "Jamón cocido, enlatado", "1.3" },
            new String[] { "965", "Cooked ham, category n/e", "Jamón cocido, categoría s/e", "0.4" },
            new String[] { "2673", "Cookie", "Galleta, genérico", "64.31" },
            new String[] { "1102", "Cookie, digestive type", "Galleta, tipo Digestiva", "63.2039" },
            new String[] { "1046", "Cookie, digestive type, with chocolate", "Galleta ,tipo digestiva, con chocolate", "66.5" },
            new String[] { "1050", "Cookie, chocolate covered", "Galleta, cubierta de chocolate", "67.4" },
            new String[] { "2672", "Cookie, salted", "Galleta salada", "69.2" },
            new String[] { "1051", "Cookie, with chocolate", "Galletas, con chocolate, tipo cookies", "64.3" },
            new String[] { "875", "Cookies, salted, with cheese", "Galletas saladas, con queso", "49.1" },
            new String[] { "2602", "Corn chips", "Fritos de maíz", "51.0" },
            new String[] { "2644", "Corn flour", "Harina de maíz", "66.3" },
            new String[] { "2551", "Corn margarine", "Margarina de maíz", "0.9" },
            new String[] { "1012", "Corn starch", "Almidón de maíz", "91.3" },
            new String[] { "879", "Corn, on the cob, frozen, raw", "Maíz, en mazorca, congelado, crudo", "18.3" },
            new String[] { "1114", "Corn, on the cob, raw", "Maíz, en mazorca, crudo", "85.6" },
            new String[] { "2517", "Cottage cheese", "Requesón", "3.3" },
            new String[] { "746", "Cotton oil", "Aceite de algodón", "0.0" },
            new String[] { "2376", "Courgette", "Calabacín", "2.0" },
            new String[] { "2377", "Courgette, roasted", "Calabacín, asado", "1.76" },
            new String[] { "2256", "Couring beef", "Cecina", "0.0" },
            new String[] { "2328", "Crab, raw", "Centollo, crudo", "0.0" },
            new String[] { "2674", "Crackers", "Galletas integrales", "42.9" },
            new String[] { "2325", "Crayfish raw", "Cangrejo de río crudo", "0.0" },
            new String[] { "810", "Crayfish, canned", "Cangrejo, en conserva", "1.0" },
            new String[] { "2489", "Cream ice cream", "Helado de nata", "24.4" },
            new String[] { "2428", "Cream liqueur 15-17% volume", "Licor de crema 15-17% vol.", "20.9" },
            new String[] { "923", "Cream, 18 % fat, uht", "Nata, líquida, para cocinar, 18% de grasa", "3.4" },
            new String[] { "2669", "Croissant", "Croissant", "55.0" },
            new String[] { "1043", "Croissant with chocolate", "Croissant de chocolate", "79.1" },
            new String[] { "2668", "Cruller", "Churro", "40.0" },
            new String[] { "2407", "Cucumber", "Pepino", "2.0" },
            new String[] { "2571", "Cumin", "Comino", "45.4" },
            new String[] { "2446", "Curaçao liqueur", "Licor curaçao", "30.0" },
            new String[] { "2485", "Curdled milk", "Cuajada", "6.6" },
            new String[] { "2515", "Cured cheese", "Queso semicurado, genérico", "0.5" },
            new String[] { "2502", "Cured cheese", "Queso curado, genérico", "0.51" },
            new String[] { "2273", "Cured ham", "Jamon serrano", "0.2" },
            new String[] { "2277", "Cured pork, loin", "Lomo embuchado", "0.0" },
            new String[] { "1161", "Cured sausage, fuet type", "Fuet", "5.5" },
            new String[] { "2621", "Curry", "Curry", "60.0" },
            new String[] { "2583", "Curry sauce", "Salsa al curry", "9.1" },
            new String[] { "787", "Custard", "Crema pastelera", "22.3" },
            new String[] { "2222", "Custard apple", "Chirimoya", "20.0" },
            new String[] { "2497", "Custard, vainilla flavored", "Natillas sabor vainilla", "15.48" },
            new String[] { "2635", "Cuttlefish", "Sepia", "0.0" },
            new String[] { "2495", "Dairy product with omega 3", "Preparado lácteo con omega 3", "5.2" },
            new String[] { "2224", "Date", "Dátil", "67.0" },
            new String[] { "962", "Deer, piece n/e, raw, with separable fat", "Ciervo, parte s/e, crudo, con grasa separable", "0.0" },
            new String[] { "830", "Derbio, frozen, raw", "Palometa, cruda", "0.0" },
            new String[] { "2618", "Dill", "Eneldo", "42.2" },
            new String[] { "821", "Dogfish, raw", "Lija, cruda", "0.0" },
            new String[] { "2670", "Doughnut", "Donut", "42.0" },
            new String[] { "1044", "Doughnut, with chocolate", "Donut, de chocolate", "51.33" },
            new String[] { "950", "Drinking yogurt, flavoured n/e", "Yogur líquido, aromatizado sabor s/e", "12.8" },
            new String[] { "1133", "Drinking yogurt, plain, sweetened", "Yogur líquido, natural, azucarado", "11.6" },
            new String[] { "1155", "Drinking yogurt, skimmed, plain", "Yogur, líquido, desnatado, natural", "12.3" },
            new String[] { "2539", "Drinking yogurt, whole milk, fruits of the forest flavoured", "Yogur, líquido, entero, sabor frutas del bosque", "15.6" },
            new String[] { "2540", "Drinking yogurt, whole milk, pineapple and coconut flavoured", "Yogur, líquido, entero, sabor piña y coco", "15.6" },
            new String[] { "2538", "Drinking yogurt, whole milk, strawberry and banana flavoured", "Yogur, líquido, entero, sabor fresa y plátano", "15.6" },
            new String[] { "2537", "Drinking yogurt, whole milk, strawberry flavoured", "Yogur, líquido, entero, sabor fresa", "15.6" },
            new String[] { "2536", "Drinking yogurt, whole milk, with fruits", "Yogur, líquido, entero, con frutas", "11.9" },
            new String[] { "2535", "Drinking yogurt, whole milk, with strawberry", "Yogur, líquido, entero, con fresas", "12.2" },
            new String[] { "976", "Duck, whole, raw", "Pato, entero, crudo", "0.0" },
            new String[] { "969", "Duck, whole, roasted", "Pato, entero, asado", "0.0" },
            new String[] { "2486", "Egg custard", "Flan de huevo", "20.4" },
            new String[] { "2126", "Egg, chicken, cooked, hard boiled", "Huevo de gallina, hervido, duro", "0.3" },
            new String[] { "760", "Egg, chicken, whole, boiled", "Huevo de gallina, pasado por agua", "0.3" },
            new String[] { "759", "Egg, chicken, whole, fried", "Huevo de gallina, frito", "0.3" },
            new String[] { "758", "Egg, chicken, whole, poached", "Huevo de gallina, escalfado", "0.3" },
            new String[] { "2127", "Egg, chicken, whole, raw", "Huevo de gallina fresco", "0.0" },
            new String[] { "762", "Egg, chicken, yolk, dried", "Huevo de gallina, yema, desecada", "2.1" },
            new String[] { "2125", "Egg, chiken, yolk, raw", "Huevo de gallina, yema, cruda", "2.3" },
            new String[] { "764", "Egg, duck, whole, raw", "Huevo de pato, crudo", "0.0" },
            new String[] { "757", "Egg, quail, whole, raw", "Huevo de codorniz, entero, crudo", "0.4" },
            new String[] { "761", "Egg, scrambled, with butter", "Huevo de gallina, revuelto, con mantequilla", "0.8" },
            new String[] { "763", "Egg, turkey, whole, raw", "Huevo de pavo, entero, crudo", "1.2" },
            new String[] { "1173", "Egg,chicken, white, raw", "Huevo de gallina, clara, cruda", "0.3" },
            new String[] { "1169", "Elver, raw", "Angula, cruda", "0.0" },
            new String[] { "2505", "Emmental cheese", "Queso emmental", "0.0" },
            new String[] { "2388", "Endive", "Endibia", "0.7" },
            new String[] { "2429", "Energy drink", "Bebida energética", "0.7" },
            new String[] { "784", "English custard", "Crema inglesa", "11.9" },
            new String[] { "2671", "Ensaimada", "Ensaimada", "38.4" },
            new String[] { "2390", "Escarole", "Escarola", "1.0" },
            new String[] { "737", "Europan eel, boiled", "Anguila, hervida", "0.0" },
            new String[] { "735", "European eel, baked", "Anguila, al horno", "0.0" },
            new String[] { "736", "European eel, raw", "Anguila, cruda", "0.0" },
            new String[] { "2544", "Extra virgin olive oil", "Aceite de oliva virgen extra", "0.0" },
            new String[] { "2545", "Extra virgin olive oil, organic ", "Aceite de oliva virgen extra, producción ecologica", "0.0" },
            new String[] { "1162", "Farm rabbit, meat, raw", "Conejo de granja, carne, cruda", "0.0" },
            new String[] { "2608", "Fennel", "Hinojo", "31.7" },
            new String[] { "2518", "Fermented milk, plain", "Leche fermentada, bifidobacterium, entera, natural", "4.4" },
            new String[] { "2227", "Figs", "Higos y brevas", "16.0" },
            new String[] { "2184", "Filbert or hazelnut, raw, in shell", "Avellana, cruda, con cáscara", "10.5" },
            new String[] { "2354", "Fish", "Pescado, genérico", "0.0" },
            new String[] { "1062", "Flaky pastry, filled with chocolate cream", "Napolitana, rellena con crema de cacao", "49.0" },
            new String[] { "2239", "Flat peach", "Paraguaya", "10.2" },
            new String[] { "2178", "Flax, seeds", "Semilla de lino", "28.88" },
            new String[] { "2542", "Flaxseed oil", "Aceite de lino", "0.0" },
            new String[] { "847", "Flying fish, raw", "Volador, crudo", "0.0" },
            new String[] { "2269", "Foie gras", "Foie gras", "3.0" },
            new String[] { "2336", "Fourspotted megrim", "Gallo", "0.0" },
            new String[] { "2309", "Frankfurt sausage", "Salchicha, tipo frankfurt", "1.3" },
            new String[] { "779", "French ommelette", "Tortilla, a la francesa", "0.4" },
            new String[] { "2516", "Fresh cheese", "Queso tierno, genérico", "0.0" },
            new String[] { "2308", "Fresh chicken sausage", "Salchicha de pollo fresca", "0.9" },
            new String[] { "786", "Fructose", "Fructosa", "100.0" },
            new String[] { "1115", "Fruit cake", "Pastel con fruta confitada", "57.0" },
            new String[] { "2240", "Fruit paste", "Pasta de fruta", "62.2" },
            new String[] { "943", "Fruit salad, canned in own juice", "Macedonia de frutas, conserva en su jugo", "25.0" },
            new String[] { "2448", "Fruits liqueur", "Licores de frutas", "35.0" },
            new String[] { "2361", "Garlic", "Ajo", "24.3" },
            new String[] { "790", "Garlic mayonnaise, oil unspecified", "Alioli", "2.84" },
            new String[] { "2362", "Garlic, fried", "Ajo, frito", "15.97" },
            new String[] { "2573", "Garlic, powder", "Ajo, en polvo", "72.73" },
            new String[] { "2613", "Gelatin", "Gelatina", "0.0" },
            new String[] { "2333", "Gilt-head bream, griddle", "Dorada, plancha", "0.0" },
            new String[] { "815", "Gilt-head bream, raw", "Dorada, cruda", "0.0" },
            new String[] { "2441", "Gin", "Ginebra", "0.0" },
            new String[] { "2606", "Ginger", "Jengibre", "9.5" },
            new String[] { "2500", "Goat cheese, cured", "Queso cabra, curado", "0.0" },
            new String[] { "934", "Goat cheese, uncured", "Queso fresco, cabra", "1.1" },
            new String[] { "1000", "Goat's milk", "Leche de cabra", "4.4" },
            new String[] { "2676", "Gofio", "Gofio", "81.57" },
            new String[] { "2612", "Gomasio", "Gomasio", "0.14" },
            new String[] { "978", "Goose, part n/e, without skin, roasted", "Oca, sin piel, asada", "0.0" },
            new String[] { "941", "Gouda cheese", "Queso Gouda", "0.0" },
            new String[] { "2158", "Granola", "Muesli", "61.0" },
            new String[] { "791", "Grape and peach juice", "Zumo de uva y melocotón", "12.0" },
            new String[] { "754", "Grape seed oil", "Aceite de grano de uva", "0.0" },
            new String[] { "2246", "Grapefruit", "Pomelo", "5.4" },
            new String[] { "1079", "Grapefruit juice", "Zumo de pomelo, envasado", "8.8" },
            new String[] { "1099", "Grapefruit nectar", "Néctar de pomelo", "3.4" },
            new String[] { "2513", "Grated cheese", "Queso rallado, genérico", "0.0" },
            new String[] { "2397", "Green bean, boiled", "Judia verde, hervida", "3.94" },
            new String[] { "2398", "Green bean, canned", "Judias verdes en conserva", "1.63" },
            new String[] { "878", "Green bean, frozen, raw", "Judía verde, congelada, cruda", "4.1" },
            new String[] { "2198", "Green been, raw", "Judía verde, cruda", "3.7" },
            new String[] { "1085", "Ground wheat, boiled", "Sémola de trigo, hervida", "11.0" },
            new String[] { "1084", "Ground wheat, raw", "Sémola de trigo, cruda", "70.4" },
            new String[] { "2349", "Grouper, griddle", "Mero, plancha", "0.32" },
            new String[] { "826", "Grouper, raw", "Mero, crudo", "0.0" },
            new String[] { "1011", "Gruyere cheese", "Queso Gruyer", "0.36" },
            new String[] { "1166", "Guava, canned in syrup", "Guayaba, enlatada en almíbar", "15.7" },
            new String[] { "938", "Guava, without skin, raw", "Guayaba, sin piel, cruda", "11.9" },
            new String[] { "2348", "Hake, coat in batter, deep fried", "Merluza, rebozada, frita", "3.52" },
            new String[] { "825", "Hake, frozen, raw", "Merluza, congelada, cruda", "0.0" },
            new String[] { "2347", "Hake, raw", "Merluza fresca", "0.0" },
            new String[] { "2335", "Halibut, raw", "Fletan, crudo", "0.5" },
            new String[] { "2271", "Ham, roasted", "Jamón asado", "0.0" },
            new String[] { "986", "Hare, whole, raw", "Liebre, entera, cruda", "0.0" },
            new String[] { "2219", "Hazelnut", "Avellana", "10.5" },
            new String[] { "970", "Heart, chicken, raw", "Corazón de pollo, crudo", "0.71" },
            new String[] { "966", "Heart, lamb, raw", "Corazón de cordero, crudo", "0.21" },
            new String[] { "975", "Hen, whole, raw", "Gallina, entera, cruda", "0.0" },
            new String[] { "741", "Herring, salted", "Arenque, salado", "0.0" },
            new String[] { "740", "Herring, smoked", "Arenque, ahumado", "0.0" },
            new String[] { "2643", "Honey", "Miel", "76.8" },
            new String[] { "818", "Horse mackerel, raw", "Jurel, crudo", "0.8" },
            new String[] { "2494", "human milk", "Leche materna", "7.0" },
            new String[] { "1781", "Iberian acorn-feed ham", "Jamón ibérico de bellota", "0.5" },
            new String[] { "1777", "Iberian ham of land cebo-feed", "Jamón ibérico de cebo", "0.1" },
            new String[] { "2443", "Infusion", "Infusión", "0.0" },
            new String[] { "2565", "Instant soup with pasta, maravilla type", "Sopa de sobre maravilla", "62.03" },
            new String[] { "2564", "Instant soup, dried", "Sopa de sobre, sin reconstituir", "58.24" },
            new String[] { "2585", "Iodized salt", "Sal yodada", "0.0" },
            new String[] { "2351", "Iridescent shark, raw", "Panga, cruda", "0.3" },
            new String[] { "2652", "Jelly", "Gominola, genérica", "69.95" },
            new String[] { "2653", "Jelly", "Jalea real", "65.0" },
            new String[] { "2123", "Kebab", "Kebab", "16.7" },
            new String[] { "1168", "Kefir", "Kefir", "4.8" },
            new String[] { "2605", "Ketchup", "Ketchup", "21.7" },
            new String[] { "686", "Kid, part n/e, raw, with separable fat", "Cabrito, parte s/e, crudo, con grasa separable", "0.0" },
            new String[] { "1063", "Kidney, lamb, raw", "Riñón, de cordero, crudo", "0.0" },
            new String[] { "1069", "Kidney, veal, raw", "Riñón, de ternera, crudo", "0.0" },
            new String[] { "2228", "Kiwi", "Kiwi", "10.6" },
            new String[] { "933", "Lamb and cow cheese, castilla-león type", "Queso de Castilla-León, oveja y vaca", "0.0" },
            new String[] { "931", "Lamb and goat cheese, castilla-la mancha type", "Queso de Castilla-La Mancha, oveja y cabra", "0.0" },
            new String[] { "2278", "Lamb gizzard", "Molleja de cordero", "0.0" },
            new String[] { "2299", "Lamb lung, raw", "Pulmón, de cordero, crudo", "0.0" },
            new String[] { "2379", "Lamb's lettuce", "Canonigos", "0.7" },
            new String[] { "932", "Lamb, cow and goat cheese, castilla-la mancha type", "Queso de Castilla-La Mancha, oveja, vaca y cabra", "0.0" },
            new String[] { "974", "Lamb, leg, with separable fat, baked", "Cordero, pierna, con grasa, asada", "0.0" },
            new String[] { "2267", "Lamb, not specified part", "Cordero, parte sin especificar", "0.0" },
            new String[] { "2266", "Lamb, rib, raw", "Cordero, costilla, crudo", "0.0" },
            new String[] { "2276", "Lamb, tongue, raw", "Lengua de cordero, cruda", "0.0" },
            new String[] { "2604", "Lasagne", "Lasaña", "10.3" },
            new String[] { "2411", "Leek, raw, frozen", "Puerro, crudo y congelado", "3.7" },
            new String[] { "937", "Lemon juice, fresh", "Zumo de limón, fresco", "3.6" },
            new String[] { "2449", "Lemonade", "Limonada", "1.9" },
            new String[] { "2200", "Lentil, boiled", "Lenteja, hervida", "54.8" },
            new String[] { "1126", "Lentil, canned", "Lenteja, en conserva", "11.4" },
            new String[] { "1065", "Lentil, dried, raw", "Lenteja, seca, cruda", "48.6954" },
            new String[] { "2399", "Lettuce", "Lechuga", "1.4" },
            new String[] { "1182", "Lightly-fried vegatables", "Sofrito", "4.71" },
            new String[] { "1089", "Lime juice", "Zumo de lima, envasado", "3.2" },
            new String[] { "1001", "Lime, raw", "Lima, cruda", "1.0" },
            new String[] { "952", "Liquid yogurt, whole milk, with cereals", "Yogur líquido, entero, con cereales", "20.8" },
            new String[] { "2659", "Liquorice", "Regaliz", "71.5" },
            new String[] { "1003", "Litchis, raw", "Litchi, crudo", "14.6" },
            new String[] { "1053", "Liver, beef, raw", "Hígado, de vaca/buey, crudo", "3.5" },
            new String[] { "2270", "Liver, chicken, raw", "Higado de pollo, crudo", "1.2" },
            new String[] { "967", "Liver, pork, raw", "Hígado, de cerdo, crudo", "0.0" },
            new String[] { "2313", "Lobster", "Bogavante", "0.0" },
            new String[] { "2339", "Lobster", "Langosta", "0.0" },
            new String[] { "799", "Lobster, boiled", "Bogavante, hervido", "0.0" },
            new String[] { "2400", "Lombard", "Lombarda", "3.5" },
            new String[] { "2183", "Lupin", "Altramuz", "40.38" },
            new String[] { "2319", "Mackarel, raw", "Caballa, cruda", "0.0" },
            new String[] { "804", "Mackerel, baked", "Caballa, al horno", "0.0" },
            new String[] { "805", "Mackerel, canned in oil, drained", "Caballa, enlatada en aceite, escurrida", "0.0" },
            new String[] { "1081", "Mango juice", "Zumo de mango", "9.8" },
            new String[] { "1061", "Mango nectar", "Néctar de mango, envasado", "13.7" },
            new String[] { "1186", "Mango, without skin, raw", "Mango, crudo", "13.4" },
            new String[] { "1105", "Maracuya nectar", "Néctar de maracuyá, envasado", "12.8" },
            new String[] { "2552", "Margarine, light", "Margarina, baja en calorías", "0.4" },
            new String[] { "2675", "Maria crackers", "Galletas tipo maria", "69.0" },
            new String[] { "771", "Marmalade, apricot", "Mermelada de albaricoque", "3.4" },
            new String[] { "2654", "Marmalade, apricot and peach, light", "Mermelada de albaricoque y melocotón, baja en calorías", "53.6" },
            new String[] { "774", "Marmalade, blackberry", "Mermelada de mora", "58.7" },
            new String[] { "775", "Marmalade, orange", "Mermelada de naranja", "4.3" },
            new String[] { "772", "Marmalade, plum", "Mermelada de ciruela", "3.4" },
            new String[] { "2655", "marmalade, raspberry", "Mermelada de frambuesa", "60.9" },
            new String[] { "773", "Marmalade, red currant", "Mermelada de grosella roja", "58.7" },
            new String[] { "2656", "Marmalade, strawberry", "Mermelada de fresa", "59.6" },
            new String[] { "2657", "marmalade, strawberry, light", "Mermelada de fresa, baja en calorías", "53.6" },
            new String[] { "886", "Mashed potato and cheese, flakes", "Puré de patata y queso, en copos", "70.5" },
            new String[] { "887", "Mashed potato with milk, flakes", "Puré, de patata, con leche", "13.7" },
            new String[] { "888", "Mashed potato with vegetables, flakes", "Puré de patata, con verduras, en copos", "74.8" },
            new String[] { "2413", "mashed potato, flakes", "Puré de patata, en copos", "78.65" },
            new String[] { "2414", "Mashed potatoes and mushrooms, flakes", "Puré de patatas y champiñones, en copos", "75.2" },
            new String[] { "2554", "Mayonnaise light", "Mayonesa, baja en calorías", "10.8" },
            new String[] { "2553", "Mayonnaise sunflower oil", "Mayonesa con aceite de girasol", "5.8" },
            new String[] { "874", "Mayonnaise, olive oil, home-prepared", "Mayonesa, aceite de oliva", "0.0971" },
            new String[] { "873", "Mayonnaise, soybean oil", "Mayonesa, aceite de soja", "0.7" },
            new String[] { "2620", "Meat pasty", "Empanada de carne", "12.01" },
            new String[] { "2474", "Meatball, canned", "Albondigas en conserva", "6.8" },
            new String[] { "956", "Medlar, with skin, raw", "Níspero, con piel, crudo", "12.1" },
            new String[] { "2238", "Medlar, withouth skin, frozen", "Nispero, sin piel , congelado", "8.6" },
            new String[] { "2234", "Melon", "Melón", "6.0" },
            new String[] { "881", "Milk cap, raw", "Níscalo, crudo", "0.1" },
            new String[] { "2651", "Milk chocolate", "Chocolate con leche", "54.1" },
            new String[] { "683", "Milk shake, cacao, light", "Batido lácteo de cacao, bajo en calorías", "4.6" },
            new String[] { "2480", "Milk shake, chocolate", "Batido de chocolate", "9.8" },
            new String[] { "2481", "Milk shake, strawberry", "Batido de fresa", "11.2" },
            new String[] { "685", "Milk shake, strawberry, light", "Batido lácteo, de fresa, bajo en calorías", "22.9" },
            new String[] { "912", "Milk, semi-skimmed, dried", "Leche en polvo, semidesnatada", "43.9" },
            new String[] { "916", "Milk, semi-skimmed, pasteurized", "Leche, semidesnatada, pasteurizada", "4.6" },
            new String[] { "2492", "Milk, skimmed, condensed, with sugar", "Leche de vaca, desnatada, condensada, con azúcar", "60.0" },
            new String[] { "915", "Milk, skimmed, pasteurized", "Leche, desnatada, pasteurizada", "4.6" },
            new String[] { "913", "Milk, whipped", "Leche merengada", "10.7" },
            new String[] { "907", "Milk, whole, condensed, with sugar", "Leche condensada, entera, con azúcar", "53.65" },
            new String[] { "2156", "Millet", "Mijo", "64.4" },
            new String[] { "2680", "Mincemeat", "Carne picada", "0.0" },
            new String[] { "2426", "Mineral water", "Agua mineral, mineralización debil", "0.0" },
            new String[] { "872", "Mint, fresh", "Menta, fresca", "5.3" },
            new String[] { "2157", "Miso", "Miso", "26.47" },
            new String[] { "2624", "Monkfish, griddle", "Rape, plancha", "0.0" },
            new String[] { "838", "Monkfish, grilled", "Rape, a la parrilla", "0.0" },
            new String[] { "2623", "Monkfish, raw", "Rape, crudo", "0.0" },
            new String[] { "919", "Mousse, cottage cheese, skimmed, with fruit", "Mousse de queso fresco, desnatado, con frutas", "19.2" },
            new String[] { "918", "Mousse, cottage cheese, skimmed, with sugar", "Mousse de queso fresco, desnatado, azucarado", "11.4" },
            new String[] { "917", "Mousse, cottage cheese, with fruits", "Mousse de queso fresco, con frutas", "16.0" },
            new String[] { "2510", "Mozzarella cheese", "Queso mozzarella", "0.0" },
            new String[] { "944", "Muenster-type cheese", "Queso munster", "0.0" },
            new String[] { "2678", "Muffin", "Magdalena", "39.9" },
            new String[] { "2629", "Mullet", "Salmonete", "0.0" },
            new String[] { "2384", "Mushroom", "Champiñon", "4.0" },
            new String[] { "2419", "Mushroom", "Seta", "4.0" },
            new String[] { "2420", "Mushroom, griddle", "Seta, plancha", "0.39" },
            new String[] { "2385", "Mushrooms, canned", "Champiñones en conserva", "0.07" },
            new String[] { "2345", "Mussel", "Mejillon", "0.0" },
            new String[] { "824", "Mussel, boiled", "Mejillón, hervido", "3.18182" },
            new String[] { "823", "Mussel, canned in brine", "Mejillón, en conserva, al natural", "2.0" },
            new String[] { "2346", "Mussel, pickled", "Mejillón, en escabeche", "0.0" },
            new String[] { "2600", "Mustard", "Mostaza", "5.0" },
            new String[] { "857", "Napolitana sauce", "Salsa napolitana", "6.5" },
            new String[] { "2236", "Nectarine", "Nectarina", "9.0" },
            new String[] { "2438", "Non-alcoholic beer", "Cerveza sin alcohol", "5.4" },
            new String[] { "785", "Nougat, alicante type", "Turrón, tipo Alicante", "44.9" },
            new String[] { "2599", "Nutmeg", "Nuez moscada", "49.29" },
            new String[] { "2189", "Nuts", "Frutos secos", "25.35" },
            new String[] { "1054", "Oat flour", "Harina de avena", "57.7" },
            new String[] { "1055", "Oat flour, boiled in water", "Harina de avena, cocida en agua", "8.0" },
            new String[] { "1010", "Oat, raw", "Avena, cruda", "66.3" },
            new String[] { "2471", "Octopus", "Pulpo", "1.4" },
            new String[] { "2374", "Octopus, boiled", "Pulpo, hervido", "1.43" },
            new String[] { "2180", "Oil cake", "Torta de aceite", "21.0" },
            new String[] { "2214", "Olive", "Aceituna", "1.0" },
            new String[] { "2543", "Olive oil", "Aceite de oliva", "0.0" },
            new String[] { "2215", "Olive, black, with bone", "Aceituna negra, con hueso", "4.0" },
            new String[] { "2381", "Onion", "Cebolla", "5.3" },
            new String[] { "2383", "Onion, boiled", "Cebolla, hervida", "3.7" },
            new String[] { "2382", "Onion, roasted", "Cebolla, asada", "7.74" },
            new String[] { "2235", "Orange", "Naranja", "8.6" },
            new String[] { "2468", "Orange juice", "Zumo de naranja", "9.0" },
            new String[] { "1103", "Orange nectar", "Néctar de naranja, envasado", "10.1" },
            new String[] { "2598", "oregano, dried", "Orégano, seco", "68.92" },
            new String[] { "2253", "Ostrich, sirloin, raw", "Avestruz, solomillo, crudo", "0.0" },
            new String[] { "2301", "Oxtail", "Rabo de toro", "0.0" },
            new String[] { "829", "Oyster, raw", "Ostra, cruda", "2.76" },
            new String[] { "2597", "Paella", "Paella", "17.44" },
            new String[] { "882", "Palm heart, canned", "Palmito, en conserva", "8.0" },
            new String[] { "751", "Palm oil", "Aceite de palma", "0.0" },
            new String[] { "803", "Pandora, raw", "Breca, cruda", "1.0" },
            new String[] { "1008", "Papaya, without skin, raw", "Papaya, cruda", "7.6" },
            new String[] { "2592", "paprika, powder", "Pimentón, en polvo", "38.0" },
            new String[] { "2512", "Parmesan cheese", "Queso parmesano", "0.0" },
            new String[] { "846", "Parrot fish, raw", "Vieja, cruda", "4.9" },
            new String[] { "2593", "parsley, fresh", "Perejil, fresco", "2.7" },
            new String[] { "2289", "Partridge, raw", "Perdiz, cruda", "0.0" },
            new String[] { "1077", "Pasta, filled with meat, boiled", "Pasta alimenticia, rellena con carne, hervida", "12.7" },
            new String[] { "1117", "Pasta, raw", "Pasta alimenticia, cruda", "70.9" },
            new String[] { "1076", "Pasta, whole, boiled", "Pasta alimenticia, integral, hervida", "23.2" },
            new String[] { "1074", "Pasta, whole, raw", "Pasta alimenticia, integral, cruda", "66.2" },
            new String[] { "1072", "Pasta, with egg, boiled", "Pasta alimenticia, con huevo, hervida", "22.9" },
            new String[] { "1118", "Pasta, with egg, raw", "Pasta alimenticia, con huevo, cruda", "69.2" },
            new String[] { "1073", "Pasta, with vegetables, raw", "Pasta alimenticia, con vegetales, cruda", "67.0" },
            new String[] { "2619", "Pasty, frozen, n/e", "Empanadilla", "29.74" },
            new String[] { "2193", "Pea, canned", "Guisantes en conserva", "9.7" },
            new String[] { "1049", "Pea, dried, raw", "Guisante, seco, crudo", "56.0" },
            new String[] { "1045", "Pea, frozen, boiled", "Guisante, congelado, hervido", "6.89409" },
            new String[] { "1175", "Pea, frozen, raw", "Guisante, congelado, crudo", "8.8" },
            new String[] { "2232", "Peach", "Melocotón", "9.0" },
            new String[] { "1104", "Peach nectar", "Néctar de melocotón", "4.0" },
            new String[] { "946", "Peach, dried", "Melocotón, desecado", "61.3" },
            new String[] { "979", "Peanut butter", "Crema de cacahuete", "11.2" },
            new String[] { "747", "Peanut oil", "Aceite de cacahuete", "0.0" },
            new String[] { "925", "Peanut, fried, salted", "Cacahuete, frito, salado", "8.9" },
            new String[] { "2185", "Peanut, raw, in shell", "Cacahuete, crudo, con cáscara", "7.91" },
            new String[] { "2186", "Peanut, toasted, salted", "Cacahuete, tostado, salado", "7.1" },
            new String[] { "2241", "Pear", "Pera", "10.6" },
            new String[] { "1101", "Pear nectar", "Néctar de pera, envasado", "15.7" },
            new String[] { "1013", "Pear, canned, in syrup", "Pera, enlatada en almíbar", "14.5" },
            new String[] { "968", "Pepper paté", "Paté de pimienta", "11.3" },
            new String[] { "2410", "Pepper, fried", "Pimiento, frito", "3.63" },
            new String[] { "831", "Perch, baked", "Perca, al horno", "0.0" },
            new String[] { "832", "Perch, raw", "Perca, cruda", "0.0" },
            new String[] { "798", "Periwinkle, boiled", "Bígaro, hervido", "0.0" },
            new String[] { "2213", "Persimmon", "Caqui", "15.3" },
            new String[] { "928", "Petit type cheese, liquid, strawberry flavour", "Petit líquido, sabor fresa", "14.5" },
            new String[] { "926", "Petit-suisse type cheese, chocolate flavour", "Petit suisse, chocolate", "24.7" },
            new String[] { "1007", "Petit-suisse type cheese, plain, with sugar", "Petit Suisse, natural azucarado", "14.3667" },
            new String[] { "927", "Petit-suisse type cheese, strawberry flavour", "Petit suisse, fresa", "16.7" },
            new String[] { "924", "Petit-suisse type cheese, with cereal and fruit", "Petit suïsse, cereales y fruta", "16.5" },
            new String[] { "2406", "Pickled gherkin", "Pepinillos en vinagre", "2.6" },
            new String[] { "2132", "Pickled tuna", "Atún en escabeche", "0.0" },
            new String[] { "977", "Pigeon, part n/e, without skin, roasted", "Pichón, sin piel, asado", "0.0" },
            new String[] { "822", "Pike, baked", "Lucio, al horno", "0.0" },
            new String[] { "2244", "Pine nut", "Piñon", "4.0" },
            new String[] { "2203", "Pine nut, raw, in shell", "Piñón, crudo, con cáscara", "3.9" },
            new String[] { "2242", "Pineapple", "Piña", "11.5" },
            new String[] { "1068", "Pineapple and grape juice", "Zumo de piña y uva", "13.0" },
            new String[] { "2469", "Pineapple juice", "Zumo de piña", "10.7" },
            new String[] { "1100", "Pineapple nectar", "Néctar de piña", "5.3" },
            new String[] { "1167", "Pineapple, canned, in juice", "Piña, enlatada en su jugo", "11.8447" },
            new String[] { "2197", "Pinto bean", "Judía pinta", "35.11" },
            new String[] { "900", "Pinto bean, dried, steeped, boiled", "Alubia negra, seca, remojada, hervida", "13.7" },
            new String[] { "2207", "Pistachio nut", "Pistacho", "15.7" },
            new String[] { "2589", "Pizza, precooked", "Pizza, precocinada", "22.2" },
            new String[] { "1027", "Plum nectar", "Néctar de ciruela", "3.4" },
            new String[] { "2226", "Pomegranate", "Granada", "13.7" },
            new String[] { "871", "Pop corn, without oil, without salt", "Palomitas de maíz, sin aceite, sin sal", "62.9" },
            new String[] { "2549", "Pork lard", "Manteca", "0.0" },
            new String[] { "2284", "Pork liver pate, fat 30%", "Pate de higado de cerdo, 30% de grasa", "5.0" },
            new String[] { "2263", "Pork luncheon meat", "Choped pork", "3.0" },
            new String[] { "2298", "Pork lung, raw", "Pulmón, de cerdo, crudo", "0.0" },
            new String[] { "2257", "Pork, chop, raw", "Cerdo, chuleta, crudo", "0.0" },
            new String[] { "972", "Pork, heart, raw", "Corazón, de cerdo, crudo", "1.3" },
            new String[] { "689", "Pork, leg, raw, with separable fat", "Cerdo, pierna, cruda, con grasa separable", "0.0" },
            new String[] { "2259", "Pork, loin, raw", "Cerdo, lomo, crudo", "0.0" },
            new String[] { "688", "Pork, loin, roasted", "Cerdo, lomo, asado", "0.0" },
            new String[] { "2261", "Pork, not specified part", "Cerdo, parte sin especificar", "0.0" },
            new String[] { "2258", "Pork, rib, raw", "Cerdo, costilla, crudo", "0.0" },
            new String[] { "1021", "Pork, sirloin, raw", "Cerdo, solomillo, crudo", "0.0" },
            new String[] { "961", "Pork, sirloin, roasted", "Cerdo, solomillo, asado", "0.0" },
            new String[] { "2275", "Pork, tongue, raw", "Lengua de cerdo, cruda", "0.0" },
            new String[] { "870", "Potato crips, low calorie", "Patatas chips, lights", "57.0991" },
            new String[] { "2404", "Potato, boiled", "Patata, hervida", "15.62" },
            new String[] { "883", "Potato, fried in oil unspecified, without salt", "Patata, frita con aceite s/e, sin sal", "30.0" },
            new String[] { "2405", "Potato, prefried, frozen", "Patata, prefrita, congelada", "32.79" },
            new String[] { "2403", "Potato, raw", "Patata, cruda", "15.2" },
            new String[] { "2402", "Potato, roast", "Patata, asada", "46.06" },
            new String[] { "884", "Potato, sauteed, with sunflowerseed oil", "Patata, salteada con aceite girasol", "13.992" },
            new String[] { "2334", "Pout, raw", "Faneca, cruda", "1.0" },
            new String[] { "2340", "Prawn, raw", "Langostino", "1.5" },
            new String[] { "1165", "Preserve fruit, fruit n/e, light", "Confitura, frutas s/e, baja en calorías", "55.0" },
            new String[] { "940", "Processed cheese, >60 % fidm", "Queso fundido, extragraso (>60% MG/ES)", "2.4" },
            new String[] { "2506", "Processed cheese, portions", "Queso en porciones", "2.5" },
            new String[] { "2563", "Protein supplement", "Suplemento proteico", "0.0" },
            new String[] { "2607", "Puff pastry", "Hojaldre", "44.2" },
            new String[] { "1060", "Puff pastry, raw", "Masa de hojaldre, cruda", "31.6796" },
            new String[] { "1120", "Puffed rice, breakfast cereals, enriched", "Arroz hinchado, para el desayuno, enriquecido", "87.7" },
            new String[] { "2204", "Pumpkin seeds", "Pipa de calabaza", "10.71" },
            new String[] { "1183", "Pumpkin, boiled", "Calabaza, hervida", "2.1" },
            new String[] { "2378", "Pumpkin, raw", "Calabaza, cruda", "5.6" },
            new String[] { "1006", "Quince, raw", "Membrillo, crudo", "6.3" },
            new String[] { "1083", "Quinoa, raw", "Quinoa, cruda", "49.195" },
            new String[] { "964", "Rabbit, whole, stewed", "Conejo, entero, estofado", "0.0" },
            new String[] { "723", "Raclette cheese", "Queso Raclette", "0.0" },
            new String[] { "2415", "Radish", "Rábano", "2.6" },
            new String[] { "2251", "Raisin ", "Uva pasa", "69.3" },
            new String[] { "2588", "Raisin pudding", "Pudding de pasas", "47.2" },
            new String[] { "1082", "Raisin pudding", "Pudin de pasas", "47.2268" },
            new String[] { "753", "Rape oil", "Aceite de colza", "0.0" },
            new String[] { "914", "Raspberry, raw", "Frambuesa, cruda", "7.0" },
            new String[] { "2470", "Ray, raw", "Raya, cruda", "0.8" },
            new String[] { "1178", "Red cabbage, boiled", "Col lombarda, hervida", "2.75" },
            new String[] { "1090", "Red currant juice", "Zumo de grosella roja", "13.2" },
            new String[] { "999", "Red currant, raw", "Grosella, cruda", "5.0" },
            new String[] { "1017", "Red grape, raw", "Uva negra, cruda", "15.5" },
            new String[] { "2409", "Red pepper, raw", "Pimiento rojo, crudo", "4.5" },
            new String[] { "2408", "Red pepper, whole, canned", "Pimiento morrón, en conserva", "5.2" },
            new String[] { "806", "Red rockfish, raw", "Cabracho o rascacio, crudo", "0.0" },
            new String[] { "817", "Red shrimp, frozen, peeled, raw", "Gamba roja, cruda", "0.0" },
            new String[] { "2465", "Red wine", "Vino tinto", "0.3" },
            new String[] { "2660", "Rice", "Arroz", "86.0" },
            new String[] { "893", "Rice starch", "Almidón de arroz", "85.0" },
            new String[] { "2479", "Rice with milk", "Arroz con leche", "16.4" },
            new String[] { "2661", "Rice, boiled", "Arroz, hervido", "85.28" },
            new String[] { "1009", "Rice, brown, boiled", "Arroz integral, hervido", "22.9" },
            new String[] { "904", "Rice, brown, raw", "Arroz integral, crudo", "81.3" },
            new String[] { "2176", "Ring-shaped pastry", "Rosquilla", "49.3" },
            new String[] { "2440", "Ron with soft drink", "Cubata", "7.35" },
            new String[] { "2514", "Roquefort cheese", "Queso roquefort", "0.0" },
            new String[] { "865", "Roquefort sauce", "Salsa al roquefort", "0.1942" },
            new String[] { "2586", "Rosemary", "Romero", "46.4" },
            new String[] { "1096", "Rum", "Ron", "0.0" },
            new String[] { "2617", "Russian salad", "Ensaladilla rusa", "9.76" },
            new String[] { "1112", "Rye flour", "Harina de centeno", "75.9" },
            new String[] { "1187", "Rye, raw", "Centeno, crudo", "79.8" },
            new String[] { "2475", "Saffron", "Azafrán", "61.5" },
            new String[] { "2389", "Salad", "Ensalada", "2.99" },
            new String[] { "2303", "Salami", "Salami", "1.3" },
            new String[] { "2310", "Salchichon", "Salchichón", "2.0" },
            new String[] { "839", "Salema, raw", "Salema, cruda", "7.9" },
            new String[] { "2626", "Salmon", "Salmón", "0.0" },
            new String[] { "2628", "Salmon, griddle", "Salmón, plancha", "0.0" },
            new String[] { "2476", "Sandwich", "Bocadillo", "35.28" },
            new String[] { "2459", "Sangria", "Sangría", "3.8" },
            new String[] { "2630", "Sardine", "Sardina", "0.0" },
            new String[] { "2632", "sardine, canned in oil, drained", "Sardina, enlatada, en aceite, escurrida", "0.0" },
            new String[] { "2633", "Sardine, canned, pickled", "Sardina, enlatada, en escabeche", "0.8" },
            new String[] { "2631", "Sardine, roasted", "Sardina, asada", "0.0" },
            new String[] { "2601", "Sauce, mojo picón type", "Mojo picon", "1.78" },
            new String[] { "2322", "Sausage", "Longaniza", "0.0" },
            new String[] { "988", "Sausage, país type, griddle", "Salchicha, tipo país, a la plancha", "0.86" },
            new String[] { "2305", "Sausage, fresh", "Salchicha, fresca", "0.9" },
            new String[] { "982", "Sausage, viena type", "Salchicha, tipo viena", "2.0" },
            new String[] { "852", "Savoy cabbage, raw", "Col rizada, cruda", "1.4" },
            new String[] { "2637", "Scallop", "Vieira", "0.0" },
            new String[] { "2331", "Scampi", "Cigala", "0.5" },
            new String[] { "2312", "Sea bream", "Besugo", "0.0" },
            new String[] { "866", "Sea salt", "Sal de mar", "0.0" },
            new String[] { "2344", "Seabass", "Lubina", "0.0" },
            new String[] { "2596", "Seafood paella", "Paella marinera", "25.13" },
            new String[] { "2568", "Seitan", "Seitán", "2.0" },
            new String[] { "2567", "Sesame loose change", "Sésamo molido", "0.9" },
            new String[] { "752", "Sesame oil", "Aceite de sésamo", "0.0" },
            new String[] { "1127", "Sesame, seed", "Sésamo, semilla", "10.0" },
            new String[] { "1002", "Sheep's milk", "Leche de oveja", "5.0" },
            new String[] { "2274", "Shoulder cured ham, lacon", "Lacón", "9.9" },
            new String[] { "2321", "Shrimp or common prawn", "Camarón", "1.5" },
            new String[] { "2337", "Shrimp, boiled", "Gamba, hervida", "0.0" },
            new String[] { "816", "Shrimp, frozen, raw", "Gamba quisquilla, congelada", "0.0" },
            new String[] { "856", "Sicilian sauce, hot", "Salsa siciliana, picante", "5.2" },
            new String[] { "2460", "Sidra", "Sidra", "6.0" },
            new String[] { "2223", "Skinned plum", "Ciruela, sin piel", "11.0" },
            new String[] { "2627", "Smoked salmon", "Salmón ahumado", "0.0" },
            new String[] { "2609", "Snack, gusanito type", "Gusanito", "50.9" },
            new String[] { "2326", "Snail", "Caracol", "2.0" },
            new String[] { "2311", "Sobrasada", "Sobrasada", "0.0" },
            new String[] { "1110", "Soda", "Soda", "0.0" },
            new String[] { "2507", "Soft cheese, burgos type", "Queso fresco de burgos", "2.5" },
            new String[] { "2456", "Soft drink, carbonated, orange flavoured", "Refresco, con gas, sabor naranja", "10.8" },
            new String[] { "2457", "Soft drink, cola flavoured", "Refresco, sabor cola", "10.85" },
            new String[] { "2458", "Soft drink, cola flavoured, light", "Refresco, sabor cola, bajo en calorías", "0.1" },
            new String[] { "1097", "Soft drink, orange flavoured, no carbonated", "Refresco, sabor naranja, sin gas", "9.365" },
            new String[] { "2450", "Soft drink, soda type", "Refresco tipo gaseosa", "0.0" },
            new String[] { "2455", "Soft drink, tonic water type", "Refresco tipo tónica", "9.2" },
            new String[] { "2341", "Sole", "Lenguado", "0.0" },
            new String[] { "820", "Sole, baked", "Lenguado, al horno", "0.0" },
            new String[] { "2342", "Sole, fried", "Lenguado, frito", "0.0" },
            new String[] { "2343", "Sole, griddle", "Lenguado, plancha", "0.47" },
            new String[] { "2667", "Soluble cereals, powder", "Cereales, en polvo, solubles (eko)", "89.7" },
            new String[] { "2648", "Soluble cocoa, with sugar, powder", "Cacao en polvo, azucarado", "81.02" },
            new String[] { "2431", "Soluble cocoa, with sugar, powder, light", "Cacao, en polvo, azucarado, bajo en calorías", "67.1" },
            new String[] { "2432", "Soluble coffee, powder", "Café, en polvo, soluble", "11.0" },
            new String[] { "1125", "Soy flour", "Harina de soja", "13.0" },
            new String[] { "2548", "Soy lecithin", "Lecitina de soja", "8.0" },
            new String[] { "2519", "Soy yogurt", "Batido fermentado de soja", "17.06" },
            new String[] { "2491", "Soya drink", "Bebida de soja", "5.76" },
            new String[] { "2482", "Soya shake", "Batido de soja", "3.9" },
            new String[] { "2208", "Soya, fried", "Soja, frita", "10.3" },
            new String[] { "2575", "Soya, sauce", "Salsa de soja", "6.7" },
            new String[] { "1129", "Soybean, dry, raw", "Soja, seca, cruda", "9.70344" },
            new String[] { "1122", "Soybean, dry, soaked, boiled", "Soja, seca, remojada, hervida", "3.76611" },
            new String[] { "1124", "Soybean, fresh", "Soja, fresca", "11.1" },
            new String[] { "849", "Soybean, sprouts, canned", "Soja, germinada, en conserva", "1.0" },
            new String[] { "2546", "Soye, oil", "Aceite de soja", "0.0" },
            new String[] { "1015", "Sparkling water, bottled", "Agua, con gas, embotellada", "0.0" },
            new String[] { "2436", "Sparkling wine, cava type", "Cava", "1.5" },
            new String[] { "2395", "Spinach, boiled", "Espinaca, hervida", "1.94" },
            new String[] { "2394", "Spinach, canned", "Espinaca, en conserva", "0.52" },
            new String[] { "861", "Spinach, frozen, raw", "Espinaca, picada, congelada, cruda", "1.0" },
            new String[] { "2664", "Sponge cake", "Bizcocho", "39.6" },
            new String[] { "2430", "Sport drink", "Bebida isotónica", "7.9" },
            new String[] { "850", "Spring onion, raw", "Cebollino, crudo", "1.9" },
            new String[] { "2323", "Squid in vegetable oil", "Calamares en aceite vegetal", "0.6" },
            new String[] { "1164", "Squid, canned", "Calamar, conserva", "0.5" },
            new String[] { "807", "Squid, raw", "Calamar, crudo", "1.09091" },
            new String[] { "2320", "Squid, roasted", "Calamar, asado", "0.5" },
            new String[] { "2622", "Stock cube", "Cubito de caldo", "5.0" },
            new String[] { "2520", "Strained yogurt", "Yogur griego", "5.4" },
            new String[] { "2225", "Strawberry", "Fresa", "7.0" },
            new String[] { "2488", "Strawberry ice cream", "Helado de fresa", "27.6" },
            new String[] { "780", "Sugar, brown", "Azúcar, moreno", "97.6" },
            new String[] { "2642", "Sugar, white", "Azúcar blanca", "100.0" },
            new String[] { "2541", "Sunflower oil", "Aceite de girasol", "0.0" },
            new String[] { "2205", "Sunflower seeds", "Pipa de girasol", "20.0" },
            new String[] { "2206", "Sunflower seeds, peeled, with salt", "Pipas de girasol, peladas, con sal", "12.8" },
            new String[] { "2562", "Surimi", "Surimi", "6.1" },
            new String[] { "2584", "Sweet and sour sauce", "Salsa agridulce", "23.99" },
            new String[] { "731", "Sweet potato, raw", "Boniato, crudo", "23.0" },
            new String[] { "2463", "Sweet wine, oporto type", "Vino dulce, tipo oporto", "14.0" },
            new String[] { "2359", "Swiss chard, canned", "Acelga, en conserva", "2.3" },
            new String[] { "2356", "Swordfish, griddle", "Pez espada, emperador, plancha", "1.28" },
            new String[] { "835", "Swordfish, raw", "Pez espada, crudo", "0.0" },
            new String[] { "2233", "Syrup peach", "Melocotón en almíbar", "13.8" },
            new String[] { "2243", "Syrup pineapple", "Piña en almíbar", "15.4" },
            new String[] { "2561", "Tabasco, sauce", "Tabasco", "0.8" },
            new String[] { "2229", "Tangerine", "Mandarina", "9.0" },
            new String[] { "2230", "Tangerine, frozen", "Mandarina, congelada", "9.2" },
            new String[] { "2425", "Tap water", "Agua de la red", "0.0" },
            new String[] { "891", "Tapioca, boiled", "Tapioca, hervida", "31.0" },
            new String[] { "2175", "Tea cookie", "Pastas de te", "58.3" },
            new String[] { "1094", "Tea infusion, with milk", "Té, infusión, con leche", "2.45" },
            new String[] { "2453", "Tea soft drink", "Refresco de té", "9.09" },
            new String[] { "2454", "Tea soft drink light", "Refresco de té, bajo en calorías", "0.0" },
            new String[] { "843", "Tench, raw", "Tenca, cruda", "3.3" },
            new String[] { "2461", "Tequila", "Tequila", "0.0" },
            new String[] { "827", "Thicklip grey mullet, baked", "Mújol, al horno", "0.0" },
            new String[] { "828", "Thicklip grey mullet, raw", "Mújol, crudo", "0.8" },
            new String[] { "2559", "Thyme", "Tomillo", "57.1" },
            new String[] { "2442", "Tigger nut milk drink", "Horchata", "17.0" },
            new String[] { "971", "Tigger nut, raw", "Chufa, cruda", "42.5402" },
            new String[] { "1121", "Tofu", "Tofu", "3.3" },
            new String[] { "2421", "Tomato", "Tomate", "3.5" },
            new String[] { "2248", "Tomato, fresh juice", "Zumo de tomate, fresco", "2.96" },
            new String[] { "2560", "Tomato, fried", "Tomate frito", "5.2" },
            new String[] { "2423", "tomato, ripe, peeled and ground, canned", "Tomate, maduro, pelado y triturado, enlatado", "5.55" },
            new String[] { "892", "Tomato, ripe, puree", "Tomate, maduro, puré", "12.9" },
            new String[] { "2422", "Tomato, roasted", "Tomate, asado", "3.43" },
            new String[] { "983", "Tongue, ox, raw", "Lengua, de buey, cruda", "3.7" },
            new String[] { "985", "Tongue, veal, roasted", "Lengua, de ternera, cruda", "0.0" },
            new String[] { "1086", "Traditional sponge cake, sobao", "Sobao", "46.7" },
            new String[] { "687", "Tripe, veal, raw", "Callos de ternera", "0.0" },
            new String[] { "1057", "Tropical fruit nectar", "Néctar de frutas exóticas, envasado", "13.2" },
            new String[] { "2636", "Trout", "Trucha", "0.0" },
            new String[] { "844", "Trout, smoked", "Trucha, ahumada", "23.6" },
            new String[] { "894", "Truffle, raw", "Trufa, cruda", "13.0" },
            new String[] { "2130", "Tuna in olive oil", "Atún en aceite de oliva isabel", "0.0" },
            new String[] { "2131", "Tuna in vegetable oil", "Atun en aceite vegetal", "0.0" },
            new String[] { "742", "Tuna, baked", "Atún, al horno", "0.0" },
            new String[] { "2133", "Tuna, canned in water", "Atún, al natural", "0.0" },
            new String[] { "2135", "Tuna, griddle", "Atún, plancha", "0.0" },
            new String[] { "2134", "Tuna, raw", "Atún, crudo", "0.0" },
            new String[] { "2625", "Turbot", "Rodaballo", "0.0" },
            new String[] { "2286", "Turkey luncheon meat", "Pavo, fiambre", "0.4" },
            new String[] { "2287", "Turkey luncheon meat, low fat", "Pavo, fiambre, bajo en grasa", "3.6" },
            new String[] { "2288", "turkey, breast, with skin, raw", "Pavo, pechuga, con piel, crudo", "0.0" },
            new String[] { "990", "Turkey, breast, without skin, grilled", "Pavo, pechuga, sin piel, a la plancha", "0.0" },
            new String[] { "1059", "Turkey, leg, with skin, raw", "Pavo, muslo, con piel, crudo", "0.0" },
            new String[] { "2285", "Turkey, raw", "Pavo, crudo", "0.0" },
            new String[] { "2396", "Turnip greens", "Grelo", "0.1" },
            new String[] { "880", "Turnip, peeled, raw", "Nabo, pelado, crudo", "3.2" },
            new String[] { "939", "Uncured cheese, skimmed, with fruit", "Queso fresco, desnatado, con frutas", "15.3" },
            new String[] { "2558", "Vanilla", "Vainilla", "12.7" },
            new String[] { "877", "Vanilla cream and chocolate mousse", "Crema de vainilla y mousse de chocolate", "22.5" },
            new String[] { "2639", "Variegated scallop", "Zamburiñas", "1.5" },
            new String[] { "2300", "Veal lung, raw", "Pulmón, de ternera, crudo", "0.0" },
            new String[] { "991", "Veal, loin, raw, with separable fat", "Ternera, lomo, crudo, con grasa separable", "0.0" },
            new String[] { "2315", "Veal, not specified part, raw, with separable fat", "Ternera, parte sin especificar, cruda, con grasa separable", "0.0" },
            new String[] { "989", "Veal, part n/e, roasted, with separable fat", "Ternera, parte s/e, asada", "0.0" },
            new String[] { "1030", "Veal, rib, raw, with separable fat", "Ternera, costilla, cruda", "0.0" },
            new String[] { "1029", "Veal, sirloin, raw, with separable fat", "Ternera, solomillo, sin grasa, crudo", "0.0" },
            new String[] { "984", "Veal, sirloin, roasted, with separable fat", "Ternera, solomillo, asado", "0.0" },
            new String[] { "792", "Vegetable stock", "Caldo vegetal", "9.1" },
            new String[] { "2401", "Vegetables, stewed, frozen", "Menestra de verduras, congelada", "6.6" },
            new String[] { "1095", "Vermuth, n/e", "Vermut, s/e", "13.5" },
            new String[] { "855", "Vinaigrette sauce, with olive oil", "Salsa vinagreta, con aceite de oliva", "0.2" },
            new String[] { "2572", "Vitamin complex", "Complejo vitaminico", "18.78" },
            new String[] { "1092", "Vodka", "Vodka", "0.0" },
            new String[] { "2201", "Walnut", "Nuez", "3.3" },
            new String[] { "750", "Walnut oil", "Aceite de nuez", "0.0" },
            new String[] { "2202", "Walnut, raw, in shell", "Nuez, cruda, con cáscara", "3.3" },
            new String[] { "732", "Watercress, raw", "Berro, crudo", "0.3" },
            new String[] { "2247", "Watermelon", "Sandía", "4.5" },
            new String[] { "789", "Wheat appetizer", "Aperitivos de trigo", "58.2" },
            new String[] { "2574", "Wheat crusts", "Corteza de trigo", "52.19" },
            new String[] { "2677", "Wheat flour", "Harina de trigo", "71.5" },
            new String[] { "1111", "Wheat germ", "Germen de trigo", "33.3" },
            new String[] { "749", "Wheat germ oil", "Aceite de germen de trigo", "0.0" },
            new String[] { "895", "Wheat starch", "Almidón de trigo", "86.1" },
            new String[] { "1113", "Wheat whole flour", "Harina de trigo, integral", "62.6" },
            new String[] { "2177", "Wheat, bran", "Salvado de trigo", "21.72" },
            new String[] { "1088", "Wheat, whole, raw", "Trigo, entero, crudo", "61.0" },
            new String[] { "2555", "Whipped cream", "Nata montada", "3.27" },
            new String[] { "2466", "Whisky", "Whisky", "0.11" },
            new String[] { "2196", "White bean", "Judía blanca", "34.7" },
            new String[] { "2199", "White bean, boiled", "Judías blancas, cocidas", "54.8" },
            new String[] { "898", "White bean, canned", "Alubia blanca, en conserva", "15.7" },
            new String[] { "899", "White bean, dried, raw", "Alubia blanca, seca, cruda", "41.6364" },
            new String[] { "2650", "White chocolate", "Chocolate blanco", "58.8" },
            new String[] { "2250", "White grape, frozen", "Uva blanca, congelada", "16.1" },
            new String[] { "2249", "White grapes", "Uva blanca", "16.1" },
            new String[] { "2591", "white pepper", "Pimienta, blanca", "42.4" },
            new String[] { "2462", "White wine", "Vino blanco", "0.1" },
            new String[] { "2136", "Whiting", "Bacaladilla", "0.0" },
            new String[] { "834", "Whiting, coated in batter, fried", "Pescadilla, rebozada en harina, frita", "3.0" },
            new String[] { "1174", "Whiting, frozen, raw", "Pescadilla, congelada, cruda", "0.0" },
            new String[] { "2493", "Whole milk", "Leche de vaca, entera", "4.7" },
            new String[] { "837", "Wide-eyed flounder, raw", "Platija, cruda", "0.0" },
            new String[] { "836", "Wide-eyed flounder, steamed", "Platija, al vapor", "0.0" },
            new String[] { "2124", "Wine vinegar", "Vinagre de vino", "0.6" },
            new String[] { "2464", "Wine, rose", "Vino rosado", "1.4" },
            new String[] { "1172", "Yellow plum, with skin, raw", "Ciruela, con piel, cruda", "12.0" },
            new String[] { "2521", "Yoghurt liquid, type actimel", "Yogur líquido, tipo actimel", "4.4" },
            new String[] { "2532", "Yogurt , skimmed, flavoured n/e", "Yogur, desnatado, aromatizado sabor s/e", "7.0" },
            new String[] { "921", "Yogurt mousse, plain", "Mousse de yogur, natural", "15.8" },
            new String[] { "920", "Yogurt mousse, with fruits", "Mousse de yogur, con frutas", "17.7" },
            new String[] { "953", "Yogurt, bulgarian-style", "Yogur, búlgaro", "5.8" },
            new String[] { "1143", "Yogurt, enriched, plain", "Yogur, enriquecido, natural", "3.9" },
            new String[] { "1145", "Yogurt, enriched, plain, sweetened", "Yogur, enriquecido, natural, azucarado", "13.5" },
            new String[] { "1130", "Yogurt, enriched, plain, with cream", "Yogur, enriquecido, natural, con nata", "4.9" },
            new String[] { "1150", "Yogurt, enriched, unspecified flavour", "Yogur, enriquecido, sabor, s/e", "37.0" },
            new String[] { "1131", "Yogurt, enriched, with fruits", "Yogur, enriquecido, con frutas", "21.0" },
            new String[] { "1160", "Yogurt, liquid, whole milk, with fruits", "Yogur líquido, con frutas s/e", "14.3" },
            new String[] { "2530", "Yogurt, skimmed, plain flavour", "Yogur, desnatado, sabor natural", "6.3" },
            new String[] { "2531", "Yogurt, skimmed, plain flavour, sweetened", "Yogur, desnatado, sabor natural, azucarado", "13.8" },
            new String[] { "1158", "Yogurt, skimmed, vanilla flavour", "Yogur, desnatado, sabor vainilla", "17.1" },
            new String[] { "1141", "Yogurt, skimmed, with apple", "Yogur, desnatado, con manzana", "5.65" },
            new String[] { "955", "Yogurt, skimmed, with cereals", "Yogur, desnatado, con cereales", "8.2" },
            new String[] { "2524", "Yogurt, skimmed, with cereals, apple and plum", "Yogur, desnatado, con cereales, manzana y ciruela", "13.1" },
            new String[] { "1135", "Yogurt, skimmed, with cherry and raspberry", "Yogur, desnatado, con cereza y frambuesa", "5.65" },
            new String[] { "2527", "Yogurt, skimmed, with fruits", "Yogur, desnatado, con frutas", "13.1" },
            new String[] { "1137", "Yogurt, skimmed, with fruits of the forest", "Yogur, desnatado, con frutas del bosque", "5.65" },
            new String[] { "1144", "Yogurt, skimmed, with peach and yellow passion fruit", "Yogur, desnatado, con melocotón y maracuyá", "5.65" },
            new String[] { "2528", "Yogurt, skimmed, with peach, raspberry and fiber", "Yogur, desnatado, con melocotón, frambuesa y fibra", "9.9" },
            new String[] { "1149", "Yogurt, skimmed, with pineapple and grapefruit", "Yogur, desnatado, con piña y pomelo", "5.65" },
            new String[] { "2525", "Yogurt, skimmed, with plum, apricot and fiber", "Yogur, desnatado, con ciruela, albaricoque y fibra", "9.9" },
            new String[] { "2526", "Yogurt, skimmed, with strawberry, redcurrant and fiber", "Yogur, desnatado, con fresa, grosella y fibra", "9.9" },
            new String[] { "1140", "Yogurt, skimmed, with tropical fruits", "Yogur, desnatado, con frutas tropicales", "5.65" },
            new String[] { "2533", "Yogurt, whole milk, with cereals and strawberry", "Yogur, entero, con cereales y fresas", "11.8" },
            new String[] { "2534", "Yogurt, whole milk, with fruits of the forest", "Yogur, entero, con frutas del bosque", "11.9" },
            new String[] { "1159", "Yogurt, whole milk, with strawberry", "Yogur, entero, con fresas", "21.4" },
            new String[] { "2357", "Young hake, raw", "Pijota, cruda", "0.0" },
            new String[] { "2352", " goose barnacle ", "Percebe", "0.0" }
    };
}
